### PR TITLE
Adding logo api endpoint

### PR DESCRIPTION
**Pull request by karllhughes**
[Clearbit's logo API](https://clearbit.com/docs#logo-api) will return a logo image if they have the domain you request. This endpoint helps you create and check that the endpoint works and a logo image is returned.

### CODE REVIEW

**Comment by karllhughes** [comment]
Addresses #5

**Comment by krichprollsch** [comment]
It looks good to me. thank you!
Could-you just [squash your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before I merge please ?

**Comment by karllhughes** [comment]
I followed the instructions there, but I'm not sure if that did anything other than add a new commit message. @krichprollsch let me know if there's anything else I can do. Thanks!

**Comment by krichprollsch** [comment]
That's look good, just you did not `push -f` your branch after the rebase, but I suppose you pulled the `master` branch from origin and create a merge commit :/

Try to redo your rebase, but `push -f` your branch this time.

Rebasing your branch change the history, so the server will refuse the push until you force it.

**Comment by karllhughes** [comment]
I merged them down. Sorry I've never done this squash thing before but it says there is a conflict now. I think maybe I went back too far in history? Let me know if I can do anything else to resolve it.

**Comment by krichprollsch** [comment]
hum, don't worry, I will fix it manually.

**Comment by krichprollsch** [comment]
replaced in favour of #6

**Pull request closed without merging**
